import json
from pathlib import Path

from specvora.case_validation import validate_request_cases
from specvora.data_cases import generate_request_cases
from specvora.models import AnalysisResult
from specvora.quality_gate import evaluate_generation_gate


def generate_artifacts(result: AnalysisResult, output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    cases_by_operation = {
        operation.operation_id: generate_request_cases(operation) for operation in result.operations
    }
    request_cases = [
        case.model_dump(mode="json")
        for operation in result.operations
        for case in cases_by_operation[operation.operation_id]
    ]
    validation_models = [
        validate_request_cases(operation, cases_by_operation[operation.operation_id])
        for operation in result.operations
    ]
    validations = [validation.model_dump(mode="json") for validation in validation_models]
    quality_gate = evaluate_generation_gate(validation_models).model_dump(mode="json")
    files = {
        "quality-plan.json": json.dumps(result.model_dump(mode="json"), indent=2),
        "traceability.json": json.dumps(result.traceability, indent=2),
        "request-cases.json": json.dumps(request_cases, indent=2),
        "validation-report.json": json.dumps(validations, indent=2),
        "quality-gate.json": json.dumps(quality_gate, indent=2),
        "test_generated_api.py": _render_tests(result),
        "github-actions.yml": _render_workflow(),
    }
    written = []
    for name, content in files.items():
        target = output_dir / name
        target.write_text(content.rstrip() + "\n", encoding="utf-8")
        written.append(target)
    return written


def _render_tests(result: AnalysisResult) -> str:
    cases = [
        {
            "id": scenario.scenario_id,
            "method": operation.method,
            "path": operation.path,
            "expected": scenario.expected_statuses,
        }
        for scenario in result.scenarios
        if scenario.kind == "positive"
        for operation in result.operations
        if operation.operation_id == scenario.operation_id
    ]
    return f'''"""Generated by Specvora. Review and approve before execution."""
import os
import httpx
import pytest

CASES = {json.dumps(cases, indent=2)}

@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
def test_documented_success(case):
    base_url = os.environ["SPECVORA_BASE_URL"]
    response = httpx.request(case["method"], base_url.rstrip("/") + case["path"], timeout=10)
    assert response.status_code in case["expected"]
'''


def _render_workflow() -> str:
    return """name: Specvora generated API checks
on:
  workflow_dispatch:
jobs:
  api-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install pytest httpx
      - name: Run approved generated tests
        env:
          SPECVORA_BASE_URL: ${{ secrets.SPECVORA_BASE_URL }}
        run: pytest generated/test_generated_api.py
"""
