from __future__ import annotations

import json
from pathlib import Path

from specvora.case_validation import OperationValidation, ValidationFinding
from specvora.models import ProjectInput, WebJourney


def validate_web_journeys(project: ProjectInput) -> list[OperationValidation]:
    validations = []
    for journey in project.web_journeys:
        findings = []
        if journey.steps[0].action != "goto":
            findings.append(
                ValidationFinding(
                    case_id=journey.journey_id,
                    severity="error",
                    code="INVALID_JOURNEY",
                    message="A web journey must begin with a goto step",
                )
            )
        validations.append(
            OperationValidation(
                operation_id=f"web:{journey.journey_id}",
                cases_checked=len(journey.steps),
                valid=not findings,
                findings=findings,
            )
        )
    return validations


def generate_playwright_artifacts(project: ProjectInput, output_dir: Path) -> list[Path]:
    if not project.web_journeys or not project.web_base_url:
        return []
    playwright_dir = output_dir / "playwright"
    playwright_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "playwright-plan.json": json.dumps(
            {
                "base_url": str(project.web_base_url),
                "allowed_hosts": normalized_hosts(project.allowed_hosts),
                "journeys": [journey.model_dump(mode="json") for journey in project.web_journeys],
                "authority": "human-review-required",
            },
            indent=2,
        ),
        "playwright.config.ts": _render_config(str(project.web_base_url)),
        "test_generated_web.spec.ts": _render_tests(project.web_journeys, project.allowed_hosts),
        "package.json": _render_package(),
    }
    written = []
    for name, content in files.items():
        target = playwright_dir / name
        target.write_text(content.rstrip() + "\n", encoding="utf-8")
        written.append(target)
    return written


def _render_config(base_url: str) -> str:
    return f"""import {{ defineConfig }} from "@playwright/test";

export default defineConfig({{
  testDir: ".",
  timeout: 30_000,
  use: {{ baseURL: {json.dumps(base_url)}, trace: "retain-on-failure" }},
}});
"""


def _render_tests(journeys: list[WebJourney], allowed_hosts: list[str]) -> str:
    hosts = normalized_hosts(allowed_hosts)
    blocks = [
        'import { test, expect } from "@playwright/test";',
        "",
        "// Generated by Specvora. Human review and approval are required.",
        f"const ALLOWED_HOSTS = new Set({json.dumps(hosts)});",
        "",
        "test.beforeEach(async ({ page }) => {",
        '  await page.route("**/*", async (route) => {',
        "    const hostname = new URL(route.request().url()).hostname.toLowerCase();",
        "    if (ALLOWED_HOSTS.has(hostname)) await route.continue();",
        '    else await route.abort("blockedbyclient");',
        "  });",
        "});",
    ]
    for journey in journeys:
        blocks.extend(["", f"test({json.dumps(journey.title)}, async ({{ page }}) => {{"])
        for step in journey.steps:
            if step.action == "goto":
                blocks.append(f"  await page.goto({json.dumps(step.path)});")
            elif step.action == "click":
                blocks.append(f"  await page.locator({json.dumps(step.selector)}).click();")
            elif step.action == "fill":
                selector = json.dumps(step.selector)
                value = json.dumps(step.value)
                blocks.append(f"  await page.locator({selector}).fill({value});")
            else:
                blocks.append(
                    f"  await expect(page.locator({json.dumps(step.selector)})).toBeVisible();"
                )
        blocks.append("});")
    return "\n".join(blocks)


def normalized_hosts(allowed_hosts: list[str]) -> list[str]:
    return sorted({host.strip().lower() for host in allowed_hosts})


def _render_package() -> str:
    return json.dumps(
        {
            "private": True,
            "scripts": {"test": "playwright test test_generated_web.spec.ts"},
            "devDependencies": {"@playwright/test": "^1.55.0"},
        },
        indent=2,
    )
